### ISSUE TITLE
incremental xml file import in wordpress

### ISSUE THREAD

**Issue by heinvv** [greghub/wp-importer#1]
Hi Greghub, 

I thought you might be able to advise. 

I am working on a project for a clients, who need an incremental xml file import in WordPress. I am not sure how/where to start. 

My experience so far: importing xml file and creating cronjobs with the WP All Import Plugin. 

Do you know how I can create an endpoint on my server where the incremental updates can reach/call the server?

The provider has provided php example scripts. I guess I can use them and create the my sql database and fields for them. 

Or I could look for an existing solution?

Do you know if there is an existing solution? Or do I need to use their php scripts?

Info from provider: 

Incremental (real-time)
With this method each vehicle mutation (add/edit/delete) will be send to a page on your webserver (endpoint). This method keeps your website up-to-date with no noticable delay.

Example of the XML file: http://eigenwebsite.doorlinkenvoorraad.nl/docs/voertuig.xsd

Example of php script: http://eigenwebsite.doorlinkenvoorraad.nl/docs/voorbeeldscript_incrementeel_xml.php
Example of http post script; http://eigenwebsite.doorlinkenvoorraad.nl/docs/voorbeeldscript_incrementeel_post.php

**Comment by greghub** [comment]
Hi heinvv,
I'm sorry I cannot help, because I'm no longer doing any wordpress work and I'm not following any WP trends or news.
However I think you can check you developers parsing large XML files incrementally in other languages, like Python and then use that solution for writing a script for WP
